"""Immutable SQL snapshot for migration 2. Add future changes as new migrations."""

SQL = (
    """CREATE TABLE datasets (id INTEGER PRIMARY KEY CHECK(id=1), root TEXT NOT NULL,
       fingerprint TEXT NOT NULL, quality TEXT NOT NULL, imported_at TEXT NOT NULL)""",
    """CREATE TABLE samples (id TEXT PRIMARY KEY, logical_key TEXT NOT NULL UNIQUE,
       source TEXT NOT NULL, split TEXT NOT NULL, error_type TEXT NOT NULL,
       paths TEXT NOT NULL, hashes TEXT NOT NULL, original_raw BLOB NOT NULL,
       original_labels TEXT NOT NULL, encoding TEXT NOT NULL)""",
    """CREATE TABLE work_plans (id TEXT PRIMARY KEY, mode TEXT NOT NULL CHECK(mode IN ('pilot','production')),
       dataset_hash TEXT NOT NULL, fingerprint TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL)""",
    """CREATE TABLE work_plan_items (plan_id TEXT REFERENCES work_plans(id),
       sample_id TEXT REFERENCES samples(id), PRIMARY KEY(plan_id,sample_id))""",
    """CREATE TABLE llm_runs (id TEXT PRIMARY KEY, plan_id TEXT NOT NULL REFERENCES work_plans(id),
       config TEXT NOT NULL, config_hash TEXT NOT NULL, prompt TEXT NOT NULL, prompt_hash TEXT NOT NULL,
       schema_hash TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(plan_id,config_hash))""",
    """CREATE TABLE jobs (id TEXT PRIMARY KEY, run_id TEXT NOT NULL UNIQUE REFERENCES llm_runs(id),
       state TEXT NOT NULL CHECK(state IN ('PENDING','RUNNING','PAUSED','FAILED','COMPLETED','CANCELLED')),
       message TEXT NOT NULL DEFAULT '', heartbeat TEXT, owner TEXT)""",
    """CREATE TABLE job_items (job_id TEXT REFERENCES jobs(id), sample_id TEXT REFERENCES samples(id),
       state TEXT NOT NULL DEFAULT 'PENDING', attempts INTEGER NOT NULL DEFAULT 0,
       error TEXT NOT NULL DEFAULT '', PRIMARY KEY(job_id,sample_id))""",
    """CREATE TABLE attempts (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES jobs(id),
       sample_id TEXT NOT NULL REFERENCES samples(id), state TEXT NOT NULL, reserved_cost REAL NOT NULL,
       charged_cost REAL NOT NULL DEFAULT 0, input_tokens INTEGER NOT NULL DEFAULT 0,
       output_tokens INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL)""",
    """CREATE TABLE llm_results (run_id TEXT REFERENCES llm_runs(id), sample_id TEXT REFERENCES samples(id),
       prediction TEXT NOT NULL, raw TEXT NOT NULL, created_at TEXT NOT NULL,
       PRIMARY KEY(run_id,sample_id))""",
    """CREATE TABLE comparisons (run_id TEXT REFERENCES llm_runs(id), sample_id TEXT REFERENCES samples(id),
       result_hash TEXT NOT NULL, signals TEXT NOT NULL, required INTEGER NOT NULL,
       decision TEXT NOT NULL, PRIMARY KEY(run_id,sample_id))""",
    """CREATE TABLE reviews (revision INTEGER PRIMARY KEY AUTOINCREMENT,
       sample_id TEXT NOT NULL REFERENCES samples(id), run_id TEXT NOT NULL REFERENCES llm_runs(id),
       state TEXT NOT NULL CHECK(state IN ('DONE','DEFERRED','DRAFT')), labels TEXT NOT NULL,
       reason TEXT NOT NULL, reviewer TEXT NOT NULL, previous_revision INTEGER,
       result_hash TEXT NOT NULL, origin TEXT NOT NULL, created_at TEXT NOT NULL)""",
    "CREATE INDEX review_latest ON reviews(run_id,sample_id,revision)",
    """CREATE TABLE snapshots (id TEXT PRIMARY KEY, run_id TEXT REFERENCES llm_runs(id),
       manifest TEXT NOT NULL, created_at TEXT NOT NULL)""",
    """CREATE TABLE merge_conflicts (id TEXT PRIMARY KEY, run_id TEXT REFERENCES llm_runs(id),
       sample_id TEXT REFERENCES samples(id), payload TEXT NOT NULL, local_revision INTEGER,
       state TEXT NOT NULL DEFAULT 'OPEN', package_id TEXT NOT NULL)""",
    """CREATE TABLE exchange_packages (id TEXT PRIMARY KEY, payload_hash TEXT NOT NULL,
       imported_at TEXT NOT NULL)""",
    """CREATE TABLE golden_sets (id TEXT PRIMARY KEY, name TEXT NOT NULL,
       fingerprint TEXT NOT NULL, created_at TEXT NOT NULL)""",
    """CREATE TABLE golden_items (set_id TEXT REFERENCES golden_sets(id),
       sample_id TEXT REFERENCES samples(id), labels TEXT NOT NULL, revision INTEGER NOT NULL,
       PRIMARY KEY(set_id,sample_id))""",
    """CREATE TABLE model_evaluations (id TEXT PRIMARY KEY, name TEXT NOT NULL,
       golden_id TEXT REFERENCES golden_sets(id), payload TEXT NOT NULL, created_at TEXT NOT NULL)""",
)
